linters-settings:
  gocritic:
    disabled-checks:
      - hugeParam
    enabled-tags:
      - performance
  govet:
    check-shadowing: true
  misspell:
    locale: US
  gci:
    local-prefixes: github.com/evilmartians/lefthook
  revive:
    rules:
      - name: unused-parameter
        disabled: true

issues:
  exclude:
    # https://github.com/catenacyber/perfsprint/issues/21
    # https://github.com/catenacyber/perfsprint/issues/23
    - "^fmt\\.Sprintf can be replaced with string (addi|concatena)tion$"

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - makezero
    - mirror
    - misspell
    - nestif
    - noctx
    - nolintlint
    - perfsprint
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tagalign
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
