linters-settings:
  gocritic:
    disabled-checks:
      - hugeParam
    enabled-tags:
      - performance
  govet:
    enable:
      - shadow
  misspell:
    locale: US
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/evilmartians/lefthook)
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  unused:
    field-writes-are-uses: false
    post-statements-are-reads: true
    exported-fields-are-used: false
    parameters-are-used: true
    local-variables-are-used: false
    generated-is-used: false

issues:
  exclude:
    # https://github.com/catenacyber/perfsprint/issues/21
    - "^fmt\\.Sprintf can be replaced with string concatenation$"

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - goheader
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - mnd
    - nestif
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tagalign
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
