linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US
  gci:
    local-prefixes: github.com/evilmartians/lefthook

linters:
  disable-all: true
  enable:
   - bodyclose
   - depguard
   - dogsled
   - dupl
   - errcheck
   - exhaustive
   - exportloopref
   - gci
   - goconst
   - gocyclo
   - gocyclo
   - godot
   - godox
   - gofmt
   - gofumpt
   - goimports
   - gomnd
   - goprintffuncname
   - gosimple
   - govet
   - ineffassign
   - misspell
   - nakedret
   - nestif
   - noctx
   - nolintlint
   - revive
   - staticcheck
   - typecheck
   - unconvert
   - unparam
   - unused
   - whitespace
