linters-settings:
  gocritic:
    disabled-checks:
      - hugeParam
    enabled-tags:
      - performance
  govet:
    check-shadowing: true
  misspell:
    locale: US
  gci:
    local-prefixes: github.com/evilmartians/lefthook
  revive:
    rules:
      - name: unused-parameter
        disabled: true

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nestif
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
