linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US
  gci:
    local-prefixes: github.com/evilmartians/lefthook

linters:
  disable-all: true
  enable:
   - bodyclose
   - deadcode
   - depguard
   - dogsled
   - dupl
   - errcheck
   - exportloopref
   - exhaustive
   - goconst
   - gocyclo
   - gofmt
   - gci
   - goimports
   - goprintffuncname
   - gosimple
   - govet
   - ineffassign
   - misspell
   - nakedret
   - noctx
   - nolintlint
   - rowserrcheck
   - staticcheck
   - structcheck
   - typecheck
   - unconvert
   - unparam
   - unused
   - varcheck
   - whitespace
