assert_lefthook_installed: true
skip_lfs: true

pre-commit:
  parallel: true
  jobs:
    - name: lint & test
      glob: "*.go"
      group:
        jobs:
          - run: make lint
            tags: lint
            stage_fixed: true

          - run: make test
            tags: test

    - name: check links
      tags: docs
      run: lychee --max-concurrency 3 {staged_files}
      glob: '*.md'
      exclude:
        - CHANGELOG.md

    - name: fix typos
      tags: lint
      run: typos --write-changes {staged_files}
      stage_fixed: true

    - name: update JSON schema
      tags: docs
      run: |
        go generate gen/jsonschema.go > internal/config/jsonschema.json
        go generate gen/jsonschema.go > schema.json
        git add internal/config/jsonschema.json
        git add schema.json
      glob:
        - 'gen/jsonschema.go'
        - 'internal/config/command.go'
        - 'internal/config/config.go'
        - 'internal/config/hook.go'
        - 'internal/config/job.go'
        - 'internal/config/remote.go'
        - 'internal/config/script.go'
