assert_lefthook_installed: true
skip_lfs: true

pre-commit:
  parallel: true
  jobs:
    - name: lint & test
      glob: "*.go"
      group:
        jobs:
          - run: make lint
            stage_fixed: true

          - run: make test

    - name: check links
      run: lychee --max-concurrency 3 {staged_files}
      glob: '*.md'
      exclude:
        - CHANGELOG.md

    - name: fix typos
      run: typos --write-changes {staged_files}
      stage_fixed: true

    - name: update JSON schema
      run: go generate internal/gen/jsonschema.go > schema.json && git add schema.json
      glob:
        - 'internal/config/command.go'
        - 'internal/config/config.go'
        - 'internal/config/hook.go'
        - 'internal/config/job.go'
        - 'internal/config/remote.go'
        - 'internal/config/script.go'
