#!/bin/bash

# If can't find lefthook in global scope
# we suppose it in local npm package
if ! type lefthook >/dev/null
then
  exec npx lefthook run pre-push $@
else
  exec lefthook run pre-push $@
fi
