#!/bin/bash
# If can't find lefthook in global scope
# we suppose it in local npm package
if ! type lefthook >/dev/null
then
  exec npx lefthook run pre-commit $@
else
  exec lefthook run pre-commit $@
fi
