package command

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/spf13/afero"

	"github.com/evilmartians/lefthook/v2/internal/config"
)

const (
	claudeSettingsDir  = ".claude"
	claudeSettingsFile = "settings.json"

	codexHooksDir  = ".codex"
	codexHooksFile = "hooks.json"

	cursorHooksDir     = ".cursor"
	cursorHooksFile    = "hooks.json"
	cursorHooksVersion = 1

	lefthookRunSuffix = " run "

	lefthookBinName = "lefthook"
)

var errAIHooksMisconfigured = errors.New("ai hooks misconfigured")

// resolveLefthookBin returns the lefthook executable or command to embed in
// generated AI hook entries. Prefers the config "lefthook" setting, then
// os.Executable(), then the bare "lefthook" name as a last resort.
func resolveLefthookBin(cfg *config.Config) (bin string, quoteBin bool) {
	if cfg != nil {
		if trimmed := strings.TrimSpace(cfg.Lefthook); trimmed != "" {
			return trimmed, false
		}
	}

	exe, err := os.Executable()
	if err != nil {
		return lefthookBinName, false
	}

	return filepath.Clean(exe), true
}

func lefthookRunCommand(bin, hookName string, quoteBin bool) string {
	if quoteBin {
		bin = shellQuotePath(bin)
	}

	return bin + lefthookRunSuffix + hookName
}

func shellQuotePath(path string) string {
	if !strings.Contains(path, " ") {
		return path
	}

	return "'" + strings.ReplaceAll(path, "'", "'\\''") + "'"
}

// isLefthookRunCommand reports whether a shell command was generated by lefthook
// to run a hook. Matches both legacy "lefthook run ..." entries and absolute
// paths from os.Executable().
func isLefthookRunCommand(cmd string) bool {
	before, _, ok := strings.Cut(cmd, lefthookRunSuffix)
	if !ok {
		return false
	}

	bin := strings.Trim(before, "'\"")
	if bin == lefthookBinName {
		return true
	}

	base := lefthookBinaryBase(bin)
	return base == lefthookBinName || base == lefthookBinName+".exe"
}

func lefthookBinaryBase(bin string) string {
	if i := strings.LastIndexAny(bin, `/\`); i >= 0 {
		return bin[i+1:]
	}

	return bin
}

func checkAIHookReferences(provider string, events map[string]string, hooks map[string]*config.Hook) []string {
	var missing []string
	for event, hookName := range events {
		if _, ok := hooks[hookName]; !ok {
			missing = append(missing, fmt.Sprintf("ai.%s.%s -> %q", provider, event, hookName))
		}
	}
	return missing
}

// validateAIHooks ensures every hook name referenced under the ai: key points to
// a hook that is actually defined in the config. This catches typos early instead
// of silently writing a `lefthook run <typo>` command that fails when the agent
// event fires.
func (l *Lefthook) validateAIHooks(ai *config.AI, hooks map[string]*config.Hook) error {
	missing := checkAIHookReferences("claude", ai.Claude, hooks)
	missing = append(missing, checkAIHookReferences("codex", ai.Codex, hooks)...)
	missing = append(missing, checkAIHookReferences("cursor", ai.Cursor, hooks)...)

	if len(missing) > 0 {
		slices.Sort(missing)
		for _, msg := range missing {
			l.logger.Errorf("%s", msg)
		}
		return errAIHooksMisconfigured
	}

	return nil
}

// installAIHooks generates (or merges into) provider-specific settings files
// for each configured LLM provider under the ai: key.
func (l *Lefthook) installAIHooks(ai *config.AI, cfg *config.Config) error {
	bin, quoteBin := resolveLefthookBin(cfg)

	if len(ai.Claude) > 0 {
		path := filepath.Join(l.repo.RootPath, claudeSettingsDir, claudeSettingsFile)
		if err := l.writeAIHookFile(path, ai.Claude, bin, quoteBin); err != nil {
			return fmt.Errorf("could not write Claude settings: %w", err)
		}
		l.logger.Infof("Updated %s", path)
	}

	if len(ai.Codex) > 0 {
		path := filepath.Join(l.repo.RootPath, codexHooksDir, codexHooksFile)
		if err := l.writeAIHookFile(path, ai.Codex, bin, quoteBin); err != nil {
			return fmt.Errorf("could not write Codex hooks: %w", err)
		}
		l.logger.Infof("Updated %s", path)
	}

	if len(ai.Cursor) > 0 {
		path := filepath.Join(l.repo.RootPath, cursorHooksDir, cursorHooksFile)
		if err := l.writeCursorHookFile(path, ai.Cursor, bin, quoteBin); err != nil {
			return fmt.Errorf("could not write Cursor hooks: %w", err)
		}
		l.logger.Infof("Updated %s", path)
	}

	return nil
}

// writeAIHookFile reads an existing JSON settings file (if present), removes
// any lefthook-managed entries (commands produced by lefthook install), merges
// in the new entries derived from events, and writes the result back.
//
// Both .claude/settings.json and .codex/hooks.json share the same top-level
// structure:
//
//	{
//	  "hooks": {
//	    "<EventName>": [
//	      { "hooks": [{ "type": "command", "command": "lefthook run <hook>" }] }
//	    ]
//	  }
//	}
func (l *Lefthook) writeAIHookFile(path string, events map[string]string, bin string, quoteBin bool) error {
	existing := make(map[string]any)

	data, err := afero.ReadFile(l.fs, path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("could not read %s: %w", path, err)
	}
	if len(data) > 0 {
		if err = json.Unmarshal(data, &existing); err != nil {
			return fmt.Errorf("could not parse %s: %w", path, err)
		}
	}

	mergedHooks := stripLefthookEntries(existing)
	for event, hookName := range events {
		entry := buildHookEntry(hookName, bin, quoteBin)
		if current, ok := mergedHooks[event]; ok {
			if arr, ok := current.([]any); ok {
				mergedHooks[event] = append(arr, entry)
				continue
			}
		}
		mergedHooks[event] = []any{entry}
	}

	existing["hooks"] = mergedHooks

	out, err := json.MarshalIndent(existing, "", "  ")
	if err != nil {
		return fmt.Errorf("could not marshal %s: %w", path, err)
	}
	out = append(out, '\n')

	dir := filepath.Dir(path)
	if mkErr := l.fs.MkdirAll(dir, hooksDirMode); mkErr != nil {
		return fmt.Errorf("could not create directory %s: %w", dir, mkErr)
	}

	return afero.WriteFile(l.fs, path, out, checksumFileMode)
}

// writeCursorHookFile reads an existing .cursor/hooks.json (if present), removes
// any lefthook-managed entries (commands produced by lefthook install), merges
// in the new entries derived from events, and writes the result back.
//
// Cursor hooks use a flat structure:
//
//	{
//	  "version": 1,
//	  "hooks": {
//	    "<eventName>": [
//	      { "command": "lefthook run <hook>" }
//	    ]
//	  }
//	}
func (l *Lefthook) writeCursorHookFile(path string, events map[string]string, bin string, quoteBin bool) error {
	existing := make(map[string]any)

	data, err := afero.ReadFile(l.fs, path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("could not read %s: %w", path, err)
	}
	if len(data) > 0 {
		if err = json.Unmarshal(data, &existing); err != nil {
			return fmt.Errorf("could not parse %s: %w", path, err)
		}
	}

	mergedHooks := stripCursorLefthookEntries(existing)
	for event, hookName := range events {
		entry := buildCursorHookEntry(hookName, bin, quoteBin)
		if current, ok := mergedHooks[event]; ok {
			if arr, ok := current.([]any); ok {
				mergedHooks[event] = append(arr, entry)
				continue
			}
		}
		mergedHooks[event] = []any{entry}
	}

	existing["version"] = cursorHooksVersion
	existing["hooks"] = mergedHooks

	out, err := json.MarshalIndent(existing, "", "  ")
	if err != nil {
		return fmt.Errorf("could not marshal %s: %w", path, err)
	}
	out = append(out, '\n')

	dir := filepath.Dir(path)
	if mkErr := l.fs.MkdirAll(dir, hooksDirMode); mkErr != nil {
		return fmt.Errorf("could not create directory %s: %w", dir, mkErr)
	}

	return afero.WriteFile(l.fs, path, out, checksumFileMode)
}

// stripCursorLefthookEntries reads the "hooks" object from an existing Cursor
// hooks map and drops any entries whose command was generated by lefthook.
// Non-lefthook entries are preserved as-is.
func stripCursorLefthookEntries(existing map[string]any) map[string]any {
	result := make(map[string]any)

	rawHooks, ok := existing["hooks"]
	if !ok {
		return result
	}

	hooksMap, ok := rawHooks.(map[string]any)
	if !ok {
		return result
	}

	for event, rawEntries := range hooksMap {
		entries, ok := rawEntries.([]any)
		if !ok {
			result[event] = rawEntries
			continue
		}

		var kept []any
		for _, rawEntry := range entries {
			if isCursorLefthookEntry(rawEntry) {
				continue
			}
			kept = append(kept, rawEntry)
		}

		if len(kept) > 0 {
			result[event] = kept
		}
	}

	return result
}

// isCursorLefthookEntry reports whether a Cursor hook entry was generated by lefthook.
func isCursorLefthookEntry(rawEntry any) bool {
	entry, ok := rawEntry.(map[string]any)
	if !ok {
		return false
	}

	cmd, ok := entry["command"].(string)
	return ok && isLefthookRunCommand(cmd)
}

// buildCursorHookEntry constructs a single Cursor hook that runs lefthook for hookName.
func buildCursorHookEntry(hookName, bin string, quoteBin bool) map[string]any {
	return map[string]any{
		"command": lefthookRunCommand(bin, hookName, quoteBin),
	}
}

// stripLefthookEntries reads the "hooks" object from an existing settings map
// and drops any matcher entries whose sole hook command was generated by lefthook.
// Non-lefthook entries are preserved as-is.
func stripLefthookEntries(existing map[string]any) map[string]any {
	result := make(map[string]any)

	rawHooks, ok := existing["hooks"]
	if !ok {
		return result
	}

	hooksMap, ok := rawHooks.(map[string]any)
	if !ok {
		return result
	}

	for event, rawMatchers := range hooksMap {
		matchers, ok := rawMatchers.([]any)
		if !ok {
			result[event] = rawMatchers
			continue
		}

		var kept []any
		for _, rawMatcher := range matchers {
			if isLefthookMatcher(rawMatcher) {
				continue
			}
			kept = append(kept, rawMatcher)
		}

		if len(kept) > 0 {
			result[event] = kept
		}
	}

	return result
}

// isLefthookMatcher reports whether a matcher entry was generated by lefthook.
// A lefthook-generated entry has a "hooks" array where every handler command
// is a lefthook run invocation.
func isLefthookMatcher(rawMatcher any) bool {
	matcher, ok := rawMatcher.(map[string]any)
	if !ok {
		return false
	}

	rawHandlers, ok := matcher["hooks"]
	if !ok {
		return false
	}

	handlers, ok := rawHandlers.([]any)
	if !ok || len(handlers) == 0 {
		return false
	}

	for _, rawHandler := range handlers {
		handler, ok := rawHandler.(map[string]any)
		if !ok {
			return false
		}
		cmd, ok := handler["command"].(string)
		if !ok || !isLefthookRunCommand(cmd) {
			return false
		}
	}

	return true
}

// buildHookEntry constructs a single matcher group that runs lefthook for hookName.
func buildHookEntry(hookName, bin string, quoteBin bool) map[string]any {
	return map[string]any{
		"hooks": []any{
			map[string]any{
				"type":    "command",
				"command": lefthookRunCommand(bin, hookName, quoteBin),
			},
		},
	}
}
